name = "Chezmoi Shell Template"
grammar = "gotmpl"
path_suffixes = [
  "sh.tmpl",
  "bash.tmpl",
  "zsh.tmpl",
  "bashrc.tmpl",
  "dot_bashrc.tmpl",
  "private_dot_bashrc.tmpl",
  "bash_profile.tmpl",
  "dot_bash_profile.tmpl",
  "private_dot_bash_profile.tmpl",
  "bash_aliases.tmpl",
  "dot_bash_aliases.tmpl",
  "private_dot_bash_aliases.tmpl",
  "bash_logout.tmpl",
  "dot_bash_logout.tmpl",
  "private_dot_bash_logout.tmpl",
  "profile.tmpl",
  "dot_profile.tmpl",
  "private_dot_profile.tmpl",
  "zshrc.tmpl",
  "dot_zshrc.tmpl",
  "private_dot_zshrc.tmpl",
  "zshenv.tmpl",
  "dot_zshenv.tmpl",
  "private_dot_zshenv.tmpl",
  "zprofile.tmpl",
  "dot_zprofile.tmpl",
  "private_dot_zprofile.tmpl",
  "zlogin.tmpl",
  "dot_zlogin.tmpl",
  "private_dot_zlogin.tmpl",
  "zlogout.tmpl",
  "dot_zlogout.tmpl",
  "private_dot_zlogout.tmpl",
]
tab_size = 2
hard_tabs = false
